### ISSUE TITLE
Table Error

### ISSUE THREAD

**Issue by Pedramaps** [ruany/litebans-php#28]
Hi, I have a problem with the litebans online
when I'm done with configuring  and want to open my website it says: no tables founded
I'm sure I did everything right I also checked server plugins was connected to database and also we had 7 tables in database but it keeps saying error with tables.
I will be happy if someone helps
thanks

**Comment by ruany** [comment]
Please make sure that you're using the latest version of the plugin (2.2.5)

**Comment by StijnSimons** [comment]
I've found the issue, the plugin does not create the config table anymore. You can fix this by replacing line 185 in `inc/settings.php`.
(`$st = $this->conn->query("SELECT * FROM " . $this->table['config'] . " LIMIT 1;");`)
to
(`$st = $this->conn->query("SELECT * FROM " . $this->table['bans'] . " LIMIT 1;");`)

Might make a pull request to fix this.

**Comment by StijnSimons** [comment]
Fixxed in pull request #29 , waiting for merge.

**Comment by kubo6472** [comment]
My error too, StijnSimons it works now

**Comment by ruany** [comment]
I've tested with the latest version of LiteBans, the config table is created on startup, even with a new table prefix.
It would be helpful if you could provide any useful information, e.g. startup errors which prevent the table from being created. Otherwise, I will not fix this as I cannot replicate the issue -- your setup has a problem if the config table isn't created, because it's required for the plugin to function properly.

**Comment by kubo6472** [comment]
Replicated using this one http://blackspigot.com/downloads/litebans-official-bsmc-release.345/

**Comment by ruany** [comment]
Illegally redistributed versions of the plugin are not supported here.

**Comment by kubo6472** [comment]
ok, sorry btw. I buyed it later.
