### ISSUE TITLE
Help me set this up?

### ISSUE THREAD

**Issue by KstreakOG** [ruany/litebans-php#7]
Hi I am currently trying to set up the plugin onto a mysql database/phpmyadmin database and I have imported the .zip into the database now I dont know where to go from here. How will the server be connected to the database how will I make the plugin on the server connect with the database and what else do I have to do! 

Thank You! 

PS: i know there is already a closed issue for this but I still dont understand

**Comment by ruany** [comment]
LiteBans and litebans-php are two entirely different things.

The web interface (litebans-php) requires the plugin (LiteBans) in order to work. The web interface will not work on its own, and the plugin does not require the web interface in order to work.
The web interface is basically an online ban-list. It's a free add-on which uses and represents data created by the plugin.

To install the plugin, you have to buy it through SpigotMC and then configure it to connect to the database. The web interface can only be used after the plugin has been installed.
